[workspace]
members = [
  "crates/fusabi-frontend",
  "crates/fusabi-vm",
  "crates/fusabi",
  "crates/fusabi-bench-compare",
  "crates/fusabi-pm",
  "crates/fusabi-lsp",
  "crates/fusabi-type-providers",
]
resolver = "2"
